services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    networks:
      - db-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\"" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  db-network:
    driver: bridge

volumes:
  postgres_data:
